apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: on-demand
spec:
  disruption:
    budgets:
      - nodes: 10%
    consolidateAfter: 120s
    consolidationPolicy: WhenEmpty
    expireAfter: 720h
  template:
    spec:
      nodeClassRef:
        name: default
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: karpenter.azure.com/sku-family
          operator: In
          values:
            - D
            - B
            - F
        - key: karpenter.azure.com/sku-name
          operator: In
          values:
            - Standard_D4s_v3
            - Standard_D8s_v3
            - Standard_D2
            - Standard_D3
            - Standard_D4_v4
            - Standard_Ds3
            - Standard_B1s
            - Standard_B2s
            - Standard_B4ms
            - Standard_B16ms
            - Standard_F1
            - Standard_F2
            - Standard_F8
            - Standard_F8s
  weight: 60
